#include <hypervisor.h>
#include <lib/stdarg.h>
#include <lib/util.h>
#include <lib/list.h>
#include <lib/macros.h>
#include <lib/rtl.h>
#include <lib/spinlock.h>
#include <lib/atomic.h>
#include <lib/types.h>
#include <lib/errno.h>
#include <lib/bits.h>
#include <lib/crypto/hkdf.h>
#include <lib/sprintf.h>
#include <lib/mem_mgt.h>
#include <hv_debug.h>
#include <common/acrn_efi.h>
#include <common/schedule.h>
#include <common/irq.h>
#include <common/ptdev.h>
#include <common/hypercall.h>
#include <debug/console.h>
#include <debug/printf.h>
#include <debug/serial.h>
#include <debug/dump.h>
#include <debug/vuart.h>
#include <debug/trace.h>
#include <debug/assert.h>
#include <debug/sbuf.h>
#include <debug/shell.h>
#include <debug/logmsg.h>
#include <hv_lib.h>
#include <public/acrn_common.h>
#include <public/acrn_hv_defs.h>
#include <arch/x86/softirq.h>
#include <arch/x86/vmexit.h>
#include <arch/x86/msr.h>
#include <arch/x86/ioapic.h>
#include <arch/x86/cpuid.h>
#include <arch/x86/multiboot.h>
#include <arch/x86/per_cpu.h>
#include <arch/x86/vtd.h>
#include <arch/x86/vmx.h>
#include <arch/x86/hv_arch.h>
#include <arch/x86/lapic.h>
#include <arch/x86/apicreg.h>
#include <arch/x86/zeropage.h>
#include <arch/x86/host_pm.h>
#include <arch/x86/timer.h>
#include <arch/x86/cpu.h>
#include <arch/x86/mtrr.h>
#include <arch/x86/assign.h>
#include <arch/x86/hob_parse.h>
#include <arch/x86/gdt.h>
#include <arch/x86/mmu.h>
#include <arch/x86/idt.h>
#include <arch/x86/io.h>
#include <arch/x86/cpufeatures.h>
#include <arch/x86/trusty.h>
#include <arch/x86/irq.h>
#include <arch/x86/guest/guest_pm.h>
#include <arch/x86/guest/vlapic.h>
#include <arch/x86/guest/vm.h>
#include <arch/x86/guest/vioapic.h>
#include <arch/x86/guest/ucode.h>
#include <arch/x86/guest/vpic.h>
#include <arch/x86/guest/vcpu.h>
#include <arch/x86/guest/guest.h>
#include <arch/x86/reboot.h>
