sudo: required

language: c

env:
   global:
      - OS_TESTED="clearlinux"

   matrix:
      - RELEASE=0
        PLATFORM=sbl

      - RELEASE=1
        PLATFORM=sbl

      - RELEASE=0
        PLATFORM=uefi

      - RELEASE=1
        PLATFORM=uefi

services:
   - docker

before_install:
   - docker build -t ${OS_TESTED} -f .travis-dockerfiles/Dockerfile.${OS_TESTED} .
   - docker images

install: true

script:
   - docker run -v $PWD:/root/acrn ${OS_TESTED} /bin/bash -c "make clean && make PLATFORM=$PLATFORM RELEASE=$RELEASE"
