DESTDIR ?=
prefix ?= /usr
bindir ?= $(prefix)/bin
libdir ?= $(prefix)/lib64
nonarchlibdir ?= $(prefix)/lib
datadir ?= $(prefix)/share
includedir ?= $(prefix)/include
systemd_unitdir ?= $(prefix)/lib/systemd
sysconfdir ?= /etc
