# Build container based on Clearlinux
FROM clearlinux:base

# python-basic-dev is only there because it gives us
# the openssl/md5.h header that we need
RUN swupd bundle-add os-core-dev dev-utils-dev

WORKDIR /root/acrn

CMD ["/bin/bash"]
