# Build container based on Ubuntu 14.04
FROM ubuntu:14.04

# Install dependencies.
RUN apt-get update \
    && apt-get install -y gcc make vim git \
                          gnu-efi \
                          libssl-dev \
                          libpciaccess-dev \
                          uuid-dev \
    && apt-get clean

WORKDIR /root/acrn

CMD ["/bin/bash"]
