/*
 * Copyright (C) 2019-2020 Intel Corporation.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef VACPI_H
#define VACPI_H

#include <acpi.h>

#define ACPI_OEM_ID           "ACRN  "

/* Use a pre-loaded multiboot module as pre-launched VM ACPI table.
 * The module file size is fixed to 1MB and loaded to GPA 0x7ff00000.
 * A hardcoded RSDP table at GPA 0x000f2400 will point to the XSDT
 * table which at GPA 0x7ff00080;
 * The module file should be generated by acrn-config tool;
 */
#define VIRT_ACPI_DATA_ADDR	0x7ff00000UL
#define VIRT_ACPI_NVS_ADDR	0x7fff0000UL
#define VIRT_RSDP_ADDR		0x000f2400UL
#define VIRT_XSDT_ADDR		0x7ff00080UL

/* virtual PCI MMCFG address base for pre/post-launched VM. */
#define UOS_VIRT_PCI_MMCFG_BASE		0xE0000000UL
#define UOS_VIRT_PCI_MMCFG_START_BUS	0x0U
#define UOS_VIRT_PCI_MMCFG_END_BUS	0xFFU

void build_vrsdp(struct acrn_vm *vm);

#endif /* VACPI_H */
