/*
 * Copyright (C) 2019-2022 Intel Corporation.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef VFDT_H
#define VFDT_H

/* Use a pre-loaded multiboot module as pre-launched VM FDT.
 * The module file should be generated by acrn-config tool;
 */
#define VIRT_FDT_LOAD_ADDR 0x80200000UL

#endif /* VFDT_H */
